### PR TITLE
AndroidRuntimeException onClick with non application context

### LINKED ISSUE #101: NullPointerException on `PubnativeDeviceUtils.isNetworkAvailable`
There's an error on `PubnativeDeviceUtils.isNetworkAvailable` that leads to a thrown `NullPointerException` we should protect this

```
Caused by java.lang.NullPointerException
net.pubnative.mediation.utils.PubnativeDeviceUtils.isNetworkAvailable (PubnativeDeviceUtils.java:64)
net.pubnative.mediation.request.PubnativeNetworkRequest.start (PubnativeNetworkRequest.java:139)
```

### PR DESCRIPTION
**Pull request by anshumansworld**
This patch tries to fix #101 

This includes check of connectivityManager to null at the time of network availability check.

### CODE REVIEW

File: mediation/src/main/java/net/pubnative/mediation/utils/PubnativeDeviceUtils.java [hunk 1]
```diff
@@ -61,7 +61,7 @@ public static boolean isNetworkAvailable(Context context) {
         Log.v(TAG, "isNetworkAvailable(Context context)");
 
         final ConnectivityManager connectivityManager = ((ConnectivityManager) context.getSystemService(Context.CONNECTIVITY_SERVICE));
-        return connectivityManager.getActiveNetworkInfo() != null && connectivityManager.getActiveNetworkInfo().isConnected();
+        return connectivityManager != null && connectivityManager.getActiveNetworkInfo() != null && connectivityManager.getActiveNetworkInfo().isConnected();
```
Comment (cerberillo) [inline mediation/src/main/java/net/pubnative/mediation/utils/PubnativeDeviceUtils.java]: We should differentiate between a connectivity issue and permissions denied, so in case of connectivity manager null, you should log an error saying that the required permission is needed

Comment (cerberillo) [inline mediation/src/main/java/net/pubnative/mediation/utils/PubnativeDeviceUtils.java]: We should also use application context to avoid weird behaviour
